<?php

/**
 * The plugin bootstrap file
 *
 * This file is read by WordPress to generate the plugin information in the plugin
 * admin area. This file also includes all of the dependencies used by the plugin,
 * registers the activation and deactivation functions, and defines a function
 * that starts the plugin.
 *
 * @link              https://https://wppb.me/
 * @since             1.0.0
 * @package           Auto_Generated
 *
 * @wordpress-plugin
 * Plugin Name:       AutoGenerated
 * Plugin URI:        https://https://wppb.me/
 * Description:       This is an auto generated wordpress plugin
 * Version:           1.0.0
 * Author:            WPPB
 * Author URI:        https://https://wppb.me/
 * License:           GPL-2.0+
 * License URI:       http://www.gnu.org/licenses/gpl-2.0.txt
 * Text Domain:       auto-generated
 * Domain Path:       /languages
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

/**
 * Currently plugin version.
 * Start at version 1.0.0 and use SemVer - https://semver.org
 * Rename this for your plugin and update it as you release new versions.
 */
define( 'AUTO_GENERATED_VERSION', '1.0.0' );

/**
 * The code that runs during plugin activation.
 * This action is documented in includes/class-auto-generated-activator.php
 */
function activate_auto_generated() {
	require_once plugin_dir_path( __FILE__ ) . 'includes/class-auto-generated-activator.php';
	Auto_Generated_Activator::activate();
}

/**
 * The code that runs during plugin deactivation.
 * This action is documented in includes/class-auto-generated-deactivator.php
 */
function deactivate_auto_generated() {
	require_once plugin_dir_path( __FILE__ ) . 'includes/class-auto-generated-deactivator.php';
	Auto_Generated_Deactivator::deactivate();
}

register_activation_hook( __FILE__, 'activate_auto_generated' );
register_deactivation_hook( __FILE__, 'deactivate_auto_generated' );

/**
 * The core plugin class that is used to define internationalization,
 * admin-specific hooks, and public-facing site hooks.
 */
require plugin_dir_path( __FILE__ ) . 'includes/class-auto-generated.php';

/**
 * Begins execution of the plugin.
 *
 * Since everything within the plugin is registered via hooks,
 * then kicking off the plugin from this point in the file does
 * not affect the page life cycle.
 *
 * @since    1.0.0
 */
function run_auto_generated() {

	$plugin = new Auto_Generated();
	$plugin->run();

}
run_auto_generated();
